### PR TITLE
Handle runlim issues

### LINKED ISSUE #25: Document/Automate handling of known runlim issue on cluster
On our cluster, `runlim` sometimes fails with `runlim error: group pid <X> larger than child pid <Y>`. 
This is a [known (open) issue](https://github.com/arminbiere/runlim/issues/8) in `runlim`.

- For a "single-process" system under test (SUT), one can avoid the issue by using the `runlim` option `--single` in the config template script (e.g. `templates/seq-generic.sh`). In that case, `{run.solver}` should either be the SUT executable or `exec` should be used if `{run.solver}` refers to a shell script.
- For other systems, one has to check for and re-run jobs that failed with a `runlim error`. To this end, one could create a script that
  - checks for and accumulates a list of failed jobs (e.g. `find $1 -name "runsolver.watcher" -exec grep -q "runlim error" {} \; -print`)
  - removes the `.finished` files of failed jobs
  - re-creates start scripts via `bgen - e`.

### PR DESCRIPTION
**Pull request by tzschmidt**
- Switch to --real-time-limit
- Update documentation
- Add helper script to handle failed jobs
- Close #25

### CODE REVIEW

File: verify_results.sh [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+
+# invalid input
+if ! [ -f $1 ]; then
+    echo "Error: provided runscript doesn't exist" >&2
+    exit 1
+fi
+
+# search runlim erros
+echo "Look for runlim errors..."
+DIR=$(cat $1 | sed -nr 's/^.*output="(\S+)".*$/\1/p')
```
Comment (BenKaufmann) [inline verify_results.sh:37]: Hm, doesn't this break for directories containing spaces?
Furthermore, I would suggest matching for `runscript output=` (optionally allowing spaces between runscript and output`) and checking whether the extracted directory exists.

File: verify_results.sh [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+    fi
+done
+
+# create new start script
+echo "Create new start script..."
+if ! [ -x "$(command -v bgen)" ]; then
+    echo "Error: benchmark-tool is not installed." >&2
+    exit 1
+fi
+bgen -e $1
```
Comment (BenKaufmann) [inline verify_results.sh:61]: Out of curiosity: It seems that we assume that the benchmark tool scripts are in the path. Is this a new requirement? So far, I always used the benchmark tool "as is" (i.e. without installation and/or conda environment).

Comment (tzschmidt) [reply verify_results.sh:61]: We switched to python entry points, so the module has to be installed. The old scripts no longer exist, see https://github.com/potassco/benchmark-tool/commit/6ede101d839c72157ffd921d3b2c12514b77efbb.

File: verify_results.sh (hunk 1 above)
Comment (tzschmidt) [reply verify_results.sh]: Should be fine now, should also support any future attributes the runscript element could get. Only thing that could cause issues is when `' '` is used instead of `" "` in the xml. But can fix that in the future if necessary.

**Review by BenKaufmann — APPROVED** [review]
